model_parameters:
  Decision Tree:
    criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson

  Random Forest:
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  Gradient Boosting:
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  Linear Regression: {}

  K-Neighbour Regressor:
    n_neighbors:
      - 5
      - 7
      - 9
      - 11

  XGBRegressor:
    learning_rate:
      - 0.1
      - 0.01
      - 0.05
      - 0.001
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256

  CatBoosting Regressor:
    depth:
      - 6
      - 8
      - 10
    iterations:
      - 30
      - 50
      - 100

  AdaBoost Regressor:
    learning_rate:
      - 0.1
      - 0.01
      - 0.5
      - 0.001
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
